name: CI
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x] # Remplace par la version de Node.js que tu utilises.

    steps:
      - name: Checkout repository âœ…
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }} ğŸ‘·
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies â¬‡ï¸
        run: npm install

      - name: Run Linter ğŸ“
        run: npm run lint

      - name: Run tests ğŸ“
        run: npm run test

      - name: Build project ğŸ—ï¸
        run: npm run build